### ISSUE TITLE
Removing the installed icons

### ISSUE THREAD

**Issue by raivivek** [sebastiencs/icons-in-terminal#4]
Hi, I tried the `install-autodetect.sh` script on my gnome-terminal and it seems to have completed successfully. However, when I ran `print_icons.sh` the icons did not show up, plus all the text on the terminal screen was garbled. I had to change the font to be able to restore sanity in the terminal.

In order to remove it, I removed the corresponding files generated by the script and updated the font-cache. However, that specific font (and the specific font-size) that was set in the terminal profile still continues the same behavior.

![image](https://user-images.githubusercontent.com/3218617/28563598-0fb8c330-7144-11e7-8868-3beeb82e19b5.png)

**Comment by sebastiencs** [comment]
Hi @vivekiitkgp 

Thanks for you report and I'm sorry to hear that, with the tests I ran on gnome-terminal everythings worked fine.

In order to remove the font, the steps you did should be enough.   
The file to delete is `~/.fonts/icons-in-terminal.ttf` and execute the command `fc-cache -fvr --really-force ~/.fonts`.   
Try to close **all** gnome-terminal windows, I know that's it's necessary with terminator. It could be the same with gnome-terminal.   
Did anything wrong happen when your ran `install-autodetect.sh` ? After running this command you restarted your terminal right ?    
Is there an output when you run `fc-list | grep icons-in-terminal` ?   
If there is no output, try to reboot your computer.   

If you have some times I'm curious about what could be the problem.
Can you give me some informations about your system ? What version of gnome-terminator are you using ?   
What distro are you using, what shell, and their versions ?

Thank you,
Sebastien

**Comment by sebastiencs** [comment]
@vivekiitkgp I've added a script to uninstall icons-in-terminal. Can you try it ?

**Comment by sebastiencs** [comment]
I'm closing the issue as I provide a script to uninstall completely `icons-in-terminal`.
@raivivek Feel free to comment here to help me to know why it didn't work for you

**Comment by raivivek** [comment]
@sebastiencs Sorry for the late post. I had uninstalled everything that day, but it seems that closing "all" gnome-terminal windows fixed it for me. I just reinstalled, closed everything, and works like a charm!

Thanks for the uninstall script. Very handy indeed.

**Comment by sebastiencs** [comment]
@raivivek Thanks for your feedback. I will add this instruction in the readme
